### ISSUE TITLE
QuickClose in TicketZoom not working

### ISSUE THREAD

**Issue by scharc** [PerlServices/opm-QuickClose#13]
QuickClose Version 6.0.5
OTRS 6.0.14

QuickClose does not work in TicketZoom. We can select the different quickClose Options but nothing happens. Any way to debug this?

**Comment by reneeb** [comment]
Can you open the developer tools of the browser (F12)? And check if there are JavaScript errors?

**Comment by reneeb** [comment]
Closed as we couldn't debug this issue... and the addon runs on many instances. Please reopen the issue when you still experience the error...
